### PR TITLE
l10n: Change to a capital letter

### PR DESCRIPTION
**Pull request by Valdnet**

### CODE REVIEW

**Review by baimard — COMMENTED** [review]
Why are you delete </div> ?

**Comment by Valdnet** [comment]
> Why are you delete ?

What am I removing? Just changing to uppercase to match all text strings for the invoice.

obraz

**Comment by baimard** [comment]
> > Why are you delete ?
> 
> What am I removing? Just changing to uppercase to match all text strings for the invoice.
> 
> obraz

line 83 check in change file

**Comment by Valdnet** [comment]
Changes are made from the level of GitHub. Apparently it deletes automatically 😁.

**Comment by Valdnet** [comment]
I added a new line to the end of the file. Is it okay?

**Pull request merged**
