### PR TITLE
l10n: Improve styling

### PR DESCRIPTION
**Pull request by Valdnet**
A more selected description of the function setting.

### CODE REVIEW

**Comment by baimard** [comment]
Just for information ? have you see the discussion in Transifex ? 

(There was lots of modifications on translation and I'm afraid of a collision between two translators)

**Comment by Valdnet** [comment]
> have you see the discussion in Transifex ?

Yes I saw. I also reported some changes myself in Transifex 😉.

Description of the change:
I deleted the word "have" (it is less necessary) and changed the word "generated" to the infinitive because the whole sentence is in the infinitive.

@rakekniven Please leave your comment for this change 😉.

**Comment by baimard** [comment]
> @rakekniven Please leave your comment for this change wink.

Wait one day for @rakekniven and after I directly merge.

Thank you very much for your contribution

**Comment by Valdnet** [comment]
> (There was lots of modifications on translation and I'm afraid of a collision between two translators)

I changed, for the consistency of words, but in my opinion the word "have" is superfluous.

**Comment by rakekniven** [comment]
@Valdnet @baimard Sounds good to me.

Thing to be aware of:
Changing the same string few times in a row of days will trigger translators also for each change. 
We have more than a hundred languages. Please keep this in mind.

**Comment by baimard** [comment]
> @Valdnet @baimard Sounds good to me.
> 
> Thing to be aware of: Changing the same string few times in a row of days will trigger translators also for each change. We have more than a hundred languages. Please keep this in mind.

even if I squash ? (to prevent analyse to each commit ?)

**Comment by Valdnet** [comment]
> even if I squash ? (to prevent analyse to each commit ?)

@baimard Rakekniven what he meant was that any change to the source text string also changes (overwrites) it in Transifex, which ends with an untranslated text string. This is the only price for the corrections made. But each translator can use the suggested translations that have occurred before, and before using it, I recommend that you compare the changes in the text strings. Requires less work on the part of the translator. It seems to me that this is not a lot of price for the correct source text strings, which reflect the popularity of the application and professionalism.

**Comment by rakekniven** [comment]
@baimard Every day 5 AM CET a sync with transifex happens. Squashing commits is not a remedy here. 

@Valdnet only a few languages have translators like you and updated translations every day. Incomplete translations do not reflect the popularity of an app 😉.

**Pull request merged**
