### PR TITLE
add Nextcloud best practice

### PR DESCRIPTION
**Pull request by sualko**
This pr will add some handy composer scripts which are recommended or at least used in many Nextcloud applications. I did not run them, especially the code style fixer, because before all changes should be merged. The vendor folder is also removed, since package dependencies should not be maintained in a git repo.

### CODE REVIEW

**Comment by baimard** [comment]
Dear @sualko,

- don't push on master
- Please test before PR

All the js script are generated by webpack, I don't see anything about that, could you please explain ?

**Comment by sualko** [comment]
> All the js script are generated by webpack, I don't see anything about that, could you please explain ?

Since the files are generated, there is no need to check them in into git and they will produce huge diffs if someone changes a source file. Another down side of adding those generated files into git is that you do not know if those files correspond to the source file. E.g. a malicious user could insert malicious code into the generated file, but not in the source.

**Comment by sualko** [comment]
If you like I could also provide a easier to read webpack config, since most of the options repeat for every entry point.

**Comment by baimard** [comment]
> > All the js script are generated by webpack, I don't see anything about that, could you please explain ?
> 
> Since the files are generated, there is no need to check them in into git and they will produce huge diffs if someone changes a source file. Another down side of adding those generated files into git is that you do not know if those files correspond to the source file. E.g. a malicious user could insert malicious code into the generated file, but not in the source.

You are right and I need to integrate a webpack deployment workflow when I publish the application. Actually, I'm the only one that change the file.

You can also compile by your self. I don't know any possibility to "compile" Javascript file at the Nextcloud installation.

> If you like I could also provide a easier to read webpack config, since most of the options repeat for every entry point.

I'm interested of that, but please PR on the dev branch and test before PR

**Comment by sualko** [comment]
> I don't know any possibility to "compile" Javascript file at the Nextcloud installation.

You do not "compile" it on the Nextcloud server. Instead you bundle it for your package/archive which is uploaded to the app store.

> I'm interested of that, but please PR on the dev branch and test before PR

To be honest it was not a pleasant first contact as a developer, so I'm not sure if I want to invest any more time into this. It's a nice application and I would really like to use it, but I have limited time and there are many interesting projects out there. Maybe one last hint: jQuery will not scale well if the application grows (I speak from experience), so it would be maybe a good idea to switch to any of the large UI frameworks. Vue is used in many Nextcloud apps and also in the core. So this is maybe a nice fit. If you stick to jQuery, please review your code, because some parts look like they could allow xss. It should not work in Nextcloud, but you can never know what the admin is doing with their csp. I wish you all the best.

**Comment by baimard** [comment]
> > I don't know any possibility to "compile" Javascript file at the Nextcloud installation.
> 
> You do not "compile" it on the Nextcloud server. Instead you bundle it for your package/archive which is uploaded to the app store.
> 
> > I'm interested of that, but please PR on the dev branch and test before PR
> 
> To be honest it was not a pleasant first contact as a developer, so I'm not sure if I want to invest any more time into this. It's a nice application and I would really like to use it, but I have limited time and there are many interesting projects out there. Maybe one last hint: jQuery will not scale well if the application grows (I speak from experience), so it would be maybe a good idea to switch to any of the large UI frameworks. Vue is used in many Nextcloud apps and also in the core. So this is maybe a nice fit. If you stick to jQuery, please review your code, because some parts look like they could allow xss. It should not work in Nextcloud, but you can never know what the admin is doing with their csp. I wish you all the best.

I confirm 3 pr in 1hour was not a pleasant contact for me too.

And for security, I'm a pentester in my real job.

**Comment by sualko** [comment]
> I confirm 3 pr in 1hour was not a pleasant contact for me too.

That implies that pull requests are a bad thing. For me they are a sign that someone is interested in your work and spends his time to help another project. It was never meant as an attack or misrespect of your work.

> And for security, I'm a pentester in my real job.

Hey cool, but that doesn't mean that you can't make mistakes too. At least I make mistakes all the time.

**Pull request closed without merging**
