### PR TITLE
avoid use of sql to migrate table

### LINKED ISSUE #123: [EN] SQL exception during update
app version before update: v1.2.5
app version to update to: v2.0.1

SQL exception:
`An exception occurred while executing a query: SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "CHANGE" LINE 1: ALTER TABLE "oc_gestion_client" CHANGE "siret" "legal_one" L... ^`

System info:
* NC version 23.0.0
* DB type: PostgreSQL v10.15
* OS: Ubuntu 20.04 LTS
* Webserver: Apache 2.4.41

### PR DESCRIPTION
**Pull request by sualko**
I did not test it, but at least this is what the api provides. I also added a type hint for table so vsc shows you some documentation.

fix #123

### CODE REVIEW

**Comment by baimard** [comment]
Dear @sualko,

- don't push on master
- Please test before PR


Are you that this change the name of column siret in legal_one?
Could you please share where you find that in the documentation ?
```
        if ($table->hasColumn('siret')) {
            $table->changeColumn('siret', [
                'type' => 'longtext',
            ]);

            $table->changeColumn('legal_one', [
                'type' => 'longtext',
            ]);
```

**Comment by sualko** [comment]
> don't push on master

Is this documented somewhere? In the Nextcloud universe the most common pattern is that the main branch is for development, because most people will open a pr for that branch.

> Are you that this change the name of column siret in legal_one?

Sorry, I read this falsely. If you want to rename it and change the type, you should maybe check the manual for a more error prone method: https://docs.nextcloud.com/server/latest/developer_manual/basics/storage/migrations.html

> Could you please share where you find that in the documentation?

In the Doctrine documentation. If you open my pr in VSC you will have autocomplete for the table variable, since I added a type hint as described above.

**Comment by baimard** [comment]
The problem of https://github.com/baimard/gestion/issues/123 is the ALTER TABLE.

According to the doctrine documentaiton, we need to use : 
```
// ...
public function up()
{
    $this->renameTable( 'old_table_name', 'new_table_name' );
}
// ...
```

But I don't know why that not work in nextcloud. I'm working on this issue.

**Comment by baimard** [comment]
> > `$this->renameTable( 'old_table_name', 'new_table_name' );`
> 
> This will rename the table, but you want to rename a column.

it's certainly why that not work :)

**Pull request closed without merging**
